### ISSUE TITLE
code for evaluation

### ISSUE THREAD

**Issue by Sharpiless** [Zhengxinyang/LAS-Diffusion#7]
Awesome work! Would you like to share your code for evaluation? Thanks.

**Comment by Zhengxinyang** [comment]
Thank you for your interest in our work. Since this piece of code is quite messy, we didn't share them. However, our metrics are fairly standard except shading-image-based FID, which you can refer to [SDF-StyleGAN](https://github.com/Zhengxinyang/SDF-StyleGAN), and I believe you can implement it by yourself easily. If you have any questions or need further clarification, please don't hesitate to reach out.

**Comment by hummat** [comment]
Hi @Zhengxinyang, again, great work! Over at [SDF-StyleGAN](https://github.com/Zhengxinyang/SDF-StyleGAN) you compare against the original ShapeNet meshes when computing shading-image-based FID, right? How is it done in this work? Do you use the original meshes again or the processed, watertight ones? Thanks!

**Comment by hummat** [comment]
@Zhengxinyang? :)
